### PR TITLE
Resizable javaFx scene example

### PR DESCRIPTION
**Pull request by encircled**

### CODE REVIEW

**Comment by encircled** [comment]
The native player always sends full-screen frame. For me such overhead is better, then stop-resize-play solution

**Comment by caprica** [comment]
Yeah, I agree that's a nice solution.

**Comment by caprica** [comment]
This code uses Platform.runLater() to get around the wrong thread errors, but I think it's accessing the native video buffer in an unsynchronised manner. In practice I suppose I've never seen an error due to this, but in theory the pixel writer is reading the native buffer at the same time as the native code is overwriting it.

**Comment by caprica** [comment]
Also let me know how you'd like to be credited in the source file.

**Comment by encircled** [comment]
I've never seen an error due to that too, but what you say sounds legit.
My name is Vladislav Kisel

**Comment by caprica** [comment]
I'm going to merge this via a patch with some minor changes rather than merge this pull request directly. That's the only reason I'm closing this request.

Thank you very much for contributing this.

**Comment by encircled** [comment]
Hi,
I have finally found the reason of the delay while opening a large video in my app that I told you about. In the ResizableJavaFXPlayerTest if you add `mediaPlayerComponent.getMediaPlayer().setTime(10000L);` (any parameter number) right after `mediaPlayerComponent.getMediaPlayer().start();` - it will take some seconds to jump. I've tested it on a medium laptop and on a high-end desktop. I wasn't able to find anything usefull from the logs or profiler. Do you have any ideas? Thanks

**Comment by caprica** [comment]
vlcj doesn't really do anything here. It just passes those media player calls to the native LibVLC API. I will try and take a look over the next few days, but I don't think I'll find anything.

**Comment by caprica** [comment]
So I have a 3.7Gb full HD mp4 file, 1920x1080 30fps.

I change the vlcj-javafx resize example as you describe with the setTime method call. No matter what I do, the video jumps instantly (well, maybe 250ms delay or so) and continues playback as normal.

I don't see any problem at all.

Now, at first after a few tests I *did* see something like the problem you describe... but what I found out was that clicking the close button for the application did not actually terminate the application! So I had 5 or 6 instances running at the same time and it seemed to jam. Once I fixed that with a proper close window handler, everything worked as expected.

**Comment by encircled** [comment]
This problem occurs on about 10 Gb files, "mkv" format. Generally, it occurs on BD quality videos I guess.

**Comment by caprica** [comment]
I don't have any video files that big to test, but I think the point is that it's unlikely there's anything systemically wrong with vlcj here, how could it be something vlcj is doing?

**Comment by encircled** [comment]
Yeah, most likely it's about the vlc lib. When opening a mkv file it always says 
```
[000000002375ad20] core decoder error: could not identify codec
[000000002375ad20] core decoder error: Unidentified codec
[000000002375ad20] core decoder error: VLC could not identify the audio or video codec
[000000002f23f170] dts decoder: DTS channels:6 samplerate:48000 bitrate:1536000
[000000002f25fcd0] core vout display error: Failed to change zoom
[000000002f25fcd0] core vout display error: Failed to set on top
[000000002f25fcd0] core vout display error: Failed to change source AR
```
Don't know if it could be a cause of my problem. 
Anyway, thanks for helping

**Comment by encircled** [comment]
Just in case someone has the same problem: it occurs only when using VLC version 2.1.5+

**Comment by caprica** [comment]
You mean *any* version of VLC from 2.1.5 onwards? Even 2.2.x?

**Comment by encircled** [comment]
I didn't try each version, but all versions below 2.1.5 that I tested were affected

**Comment by caprica** [comment]
Sorry, I don't quite understand... you said originally "it occurs only when using VLC version 2.1.5+", the implication being that in 2.1.4 and earlier there was no problem, but in 2.1.5 and later there is a problem. Yet your latest message says "all versions below 2.1.5 [...] were affected" - isn't that a contradiction?

**Comment by encircled** [comment]
Yeah, sorry, 2.1.5 and later

**Pull request closed without merging**
